image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/
test:
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod

staging:
  type: deploy
  only:
    - dev
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod