image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - dev
  script:
    - rm ./package-lock.json
    - npm install
    - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng e2e --protractor-config=./e2e/protractor-ci.conf.js
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod --base-href swatang-stage.surge.sh
    - ./node_modules/.bin/surge -p dist/ --domain swatang-stage.surge.sh