image: trion/ng-cli-karma

cache:
  paths:
    - node_modules/

deploy_stage:
  stage: deploy
  environment: Stage
  only:
    - dev
  script:
    - npm install
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod --base-href mwd-swatang-stage.surge.sh