#image: trion/ng-cli-karma
image: node:latest
before_script:
  - npm install

cache:
  paths:
    - node_modules/

# Verify it can build.
build:
  stage: build
  artifacts:
    paths:
    - dist
    expire_in: 1 day
  only:
    - merge_requests
  script:
    - npm run build

# Verify it passes linting.
test:lint:
  stage: test
  only:
    - merge_requests
  script:
    - npm run lint

test:
  only:
    - merge_requests
  script:
    - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod

staging:
  type: deploy
  only:
    - /^version-.*$/
    - improvement
  script:
    - ./node_modules/@angular/cli/bin/ng test --progress false --watch=false
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod
    - ./node_modules/.bin/surge -p dist/swatang --domain swatangv1-stage.surge.sh
