image: trion/ng-cli-karma

before_script:
  - npm install

cache:
  paths:
    - node_modules/

# Verify it can build.
build:
  stage: build
  artifacts:
    paths:
    - dist
    expire_in: 1 day
  script:
    - npm run build

# Verify it passes linting.
test:lint:
  stage: test
  script:
    - npm run lint

test:
  script:
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod

staging:
  type: deploy
  only:
    - dev
  script:
    - ./node_modules/@angular/cli/bin/ng build --progress false --prod