version: 2
jobs:
    # The build job
    build:
        working_directory: ~/fe_angular
        docker:
            - image: circleci/node:8.9.4-browsers
        steps:
            - add_ssh_keys:
                fingerprints:
                - "f1:25:ca:79:7a:4b:90:4e:d4:91:31:48:dd:e6:89:91"
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: yarn install
            - run:
                name: Build Node Sass
                command: yarn add --force node-sass
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Lint the source code
            - run:
                name: Linting
                command: yarn run lint
            # Test the source code
            - run:
                name: Testing
                command: yarn run test
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building
                command: |
                    if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                        yarn build
                    elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                        yarn build
                    else
                        yarn build
                    fi
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
            - run: cd dist
            - run: git init
            - run: git config user.name "Luong Mai"
            - run: git config user.email "mwd-luong.mai@mowede.com"
            - run: git add .
            - run: git commit -m "Deploy swatang app"
            - run: git push --force --quiet "git@github.com:mwd-luongmai/mwd-luongmai.github.io.git" master # path to your repo on GitHub, using token for authentication
    # # Deploy job
    # deploy:
    #     machine:
    #         enabled: true
    #     working_directory: ~/fe_angular
    #     steps:
    #         - run: cd dist
    #         - run: git init
    #         - run: git config user.name "Luong Mai"
    #         - run: git config user.email "mwd-luong.mai@mowede.com"
    #         - run: git add .
    #         - run: git commit -m "Deploy swatang app"
    #         - run: git push --force --quiet "https://f3429b17299461de1e5c8339d83c245b44a58e83@github.com/mwd-luongmai/mwd-luongmai.github.io.git" master # path to your repo on GitHub, using token for authentication
workflows:
    version: 2
    build-test-and-approval-deploy:
        jobs:
            - build
            - hold: # <<< A job that will require manual approval in the CircleCI web application.
                type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
                requires: # We only run the "hold" job when test2 has succeeded
                - build
            # On approval of the `hold` job, any successive job that requires the `hold` job will run. 
            # In this case, a user is manually triggering the deploy job.
            # - deploy:
            #     requires:
            #         - hold
