version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/node:8.9.4-browsers
    working_directory: ~/fe_angular
jobs:
    # The build job
    build:
        executor: my-executor
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: yarn install
            - run:
                name: Build Node Sass
                command: yarn add --force node-sass
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Lint the source code
            - run:
                name: Linting
                command: yarn run lint
            # Test the source code
            - run:
                name: Testing
                command: yarn run test
            # Build project with different configuration based on
            # the current branch
            - run:
                name: Building and Deploying to GitPage
                command: |
                    if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                        yarn build
                    elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
                        yarn build
                    elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                        yarn build
                    else
                        yarn build
                    fi
            # Cache the dist folder for the deploy job
            - save_cache:
                key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - dist
             # Persist the specified paths into the workspace for use in downstream job. 
            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
                # taken to be the root directory of the workspace.
                root: .
                # Must be relative path from root
                paths:
                    - dist
                    - package.json
                    - angular.json
                    - package-lock.json
    # The build job
    deploy-stage:
        executor: my-executor
        steps:
            - attach_workspace:
                # Must be absolute path or relative path from working_directory
                at: ~/fe_angular
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - add_ssh_keys:
                fingerprints:
                    - "e0:f6:b0:34:78:9a:24:1e:af:17:fd:1b:77:44:85:c7"
            - run:
                name: Avoid hosts unknown for github
                command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            # Deploy to GitPage
            - run: git init
            - run: git config user.name $GH_NAME
            - run: git config user.email $GH_EMAIL
            - run: git remote add origin $GH_REPO
            - run: yarn run deploy
    deploy-prod:
        executor: my-executor
        steps:
            - attach_workspace:
                # Must be absolute path or relative path from working_directory
                at: ~/fe_angular
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            - add_ssh_keys:
                fingerprints:
                    - "e0:f6:b0:34:78:9a:24:1e:af:17:fd:1b:77:44:85:c7"
            - run:
                name: Avoid hosts unknown for github
                command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
            # Deploy to GitPage
            - run: git init
            - run: git config user.name $GH_NAME
            - run: git config user.email $GH_EMAIL
            - run: git remote add origin $GH_REPO
            - run: yarn run deploy
workflows:
    version: 2
    nightly:
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - build
    commit:
        jobs:
            - build:
                filters:
                    branches:
                        ignore:
                            - gh-pages
                            - /feature-.*/
            - hold: # <<< A job that will require manual approval in the CircleCI web application.
                type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
                requires: # We only run the "hold" job when test2 has succeeded
                    - build
            # On approval of the `hold` job, any successive job that requires the `hold` job will run. 
            # In this case, a user is manually triggering the deploy job.
            - deploy-stage:
                requires:
                    - hold
                filters:
                    branches:
                        only: staging
            - deploy-prod:
                requires:
                    - hold
                filters:
                    branches:
                        only: master
